import type {
  CreateMcpServerInput,
  McpServerResponse,
} from "@nexu/shared";

/**
 * Thin fetch wrapper for the MCP server endpoints.
 *
 * The generated hey-api SDK is regenerated by `pnpm generate-types`, which is
 * not part of the build pipeline; to keep the MCP feature self-contained this
 * uses fetch directly against the same controller base URL the SDK client is
 * configured with (mirrors apps/web/src/lib/desktop-chat-stream.ts).
 */
function resolveApiBaseUrl(): string {
  const configured = import.meta.env.VITE_API_BASE_URL as string | undefined;
  const isElectronRenderer =
    typeof navigator !== "undefined" &&
    navigator.userAgent.includes("Electron");
  if (isElectronRenderer) {
    return "";
  }
  return (configured ?? "").replace(/\/+$/u, "");
}

function apiUrl(path: string): string {
  return `${resolveApiBaseUrl()}${path}`;
}

export async function listMcpServers(): Promise<McpServerResponse[]> {
  const response = await fetch(apiUrl("/api/v1/mcp-servers"), {
    credentials: "include",
  });
  if (!response.ok) {
    throw new Error(`Failed to load MCP servers (HTTP ${response.status})`);
  }
  const data = (await response.json()) as { servers: McpServerResponse[] };
  return data.servers ?? [];
}

export async function createMcpServer(
  input: CreateMcpServerInput,
): Promise<McpServerResponse> {
  const response = await fetch(apiUrl("/api/v1/mcp-servers"), {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  if (!response.ok) {
    let message = `Failed to create MCP server (HTTP ${response.status})`;
    try {
      const body = await response.json();
      if (body && typeof body === "object") {
        const record = body as Record<string, unknown>;
        // Zod validation errors come back with an issues array; surface the
        // first readable message.
        if (typeof record.message === "string") {
          message = record.message;
        }
      }
    } catch {
      // keep default message
    }
    throw new Error(message);
  }
  return (await response.json()) as McpServerResponse;
}

export async function deleteMcpServer(id: string): Promise<void> {
  const response = await fetch(
    apiUrl(`/api/v1/mcp-servers/${encodeURIComponent(id)}`),
    {
      method: "DELETE",
      credentials: "include",
    },
  );
  if (!response.ok) {
    throw new Error(`Failed to delete MCP server (HTTP ${response.status})`);
  }
}
